/*{"mac":"1:70953441628ba5dfbbbaeb8dbd0f81c3772770e587f4a7ce65f0595147f56f8a","version":"15391799","created":"2013-01-29T17:57:36Z","k":"1.2.2"}*/
/*
 * For font license information, see the CSS file loaded by this JavaScript.
 */
;(function(window,document,undefined){
var g=void 0,k=!0,l=null,m=!1;function n(a){return function(){return this[a]}}var o;function p(a,c,b){var e=2<arguments.length?Array.prototype.slice.call(arguments,2):[];return function(){e.push.apply(e,arguments);return c.apply(a,e)}}function q(a,c){this.ja=c||a;this.j=this.ja.document;this.r=g}
q.prototype.createElement=function(a,c,b){a=this.j.createElement(a);if(c)for(var e in c)c.hasOwnProperty(e)&&("style"==e?this.qa(a,c[e]):a.setAttribute(e,c[e]));b&&a.appendChild(this.j.createTextNode(b));return a};function r(a,c,b){a=a.j.getElementsByTagName(c)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(b,a.lastChild)}function s(a){function c(){document.body?a():setTimeout(c,0)}c()}function t(a){a.parentNode&&a.parentNode.removeChild(a)}
function u(a,c){for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return;b.push(c);a.className=b.join(" ").replace(/^\s+/,"")}function v(a,c){for(var b=a.className.split(/\s+/),e=[],d=0,f=b.length;d<f;d++)b[d]!=c&&e.push(b[d]);a.className=e.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")}function w(a,c){for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return k;return m}q.prototype.qa=function(a,c){this.U()?a.setAttribute("style",c):a.style.cssText=c};
q.prototype.U=function(){if(this.r===g){var a=this.j.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.r=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.r};function x(a,c,b,e,d,f,h){this.W=a;this.Pa=c;this.ya=b;this.xa=e;this.Ka=d;this.Ja=f;this.wa=h}o=x.prototype;o.getName=n("W");o.getVersion=n("Pa");o.getEngine=n("ya");o.getEngineVersion=n("xa");o.getPlatform=n("Ka");o.getPlatformVersion=n("Ja");o.getDocumentMode=n("wa");
function z(a,c){this.c=a;this.p=c}var ba=new x("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",g);
z.prototype.parse=function(){var a;if(-1!=this.c.indexOf("MSIE")){a=A(this);var c=B(this),b=C(this.c,/(MSIE [\d\w\.]+)/,1);if(""!=b){var e=b.split(" "),b=e[0],e=e[1];E(e);E(c);a=new x(b,e,b,e,a,c,F(this.p))}else a=new x("MSIE","Unknown","MSIE","Unknown",a,c,F(this.p))}else if(-1!=this.c.indexOf("Opera"))a:if(c=a="Unknown",b=C(this.c,/(Presto\/[\d\w\.]+)/,1),""!=b?(c=b.split("/"),a=c[0],c=c[1]):(-1!=this.c.indexOf("Gecko")&&(a="Gecko"),b=C(this.c,/rv:([^\)]+)/,1),""!=b&&(c=b)),-1!=this.c.indexOf("Opera Mini/"))b=
C(this.c,/Opera Mini\/([\d\.]+)/,1),""==b&&(b="Unknown"),a=new x("OperaMini",b,a,c,A(this),B(this),F(this.p));else{if(-1!=this.c.indexOf("Version/")&&(b=C(this.c,/Version\/([\d\.]+)/,1),""!=b)){a=new x("Opera",b,a,c,A(this),B(this),F(this.p),10<=E(b));break a}b=C(this.c,/Opera[\/ ]([\d\.]+)/,1);a=""!=b?new x("Opera",b,a,c,A(this),B(this),F(this.p),10<=E(b)):new x("Opera","Unknown",a,c,A(this),B(this),F(this.p))}else if(/AppleWeb(K|k)it/.test(this.c)){a=A(this);c=B(this);b=C(this.c,/AppleWeb(?:K|k)it\/([\d\.]+)/,
1);""==b&&(b="Unknown");e="Unknown";-1!=this.c.indexOf("Chrome")||-1!=this.c.indexOf("CrMo")||-1!=this.c.indexOf("CriOS")?e="Chrome":"BlackBerry"==a||"Android"==a?e="BuiltinBrowser":-1!=this.c.indexOf("Safari")?e="Safari":-1!=this.c.indexOf("AdobeAIR")&&(e="AdobeAIR");var d="Unknown";"BuiltinBrowser"==e?d="Unknown":-1!=this.c.indexOf("Version/")?d=C(this.c,/Version\/([\d\.\w]+)/,1):"Chrome"==e?d=C(this.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):"AdobeAIR"==e&&(d=C(this.c,/AdobeAIR\/([\d\.]+)/,1));"AdobeAIR"==
e?(C(d,/\d+\.(\d+)/,1),2<E(d)||E(d)):"BlackBerry"!=a&&"Android"!=a&&(C(b,/\d+\.(\d+)/,1),526<=E(b)||E(b));a=new x(e,d,"AppleWebKit",b,a,c,F(this.p))}else if(-1!=this.c.indexOf("Gecko")){c=a="Unknown";e=m;-1!=this.c.indexOf("Firefox")?(a="Firefox",b=C(this.c,/Firefox\/([\d\w\.]+)/,1),""!=b&&(e=C(b,/\d+\.(\d+)/,1),c=b,e=""!=b&&3<=E(b)&&5<=parseInt(e,10))):-1!=this.c.indexOf("Mozilla")&&(a="Mozilla");b=C(this.c,/rv:([^\)]+)/,1);if(""==b)b="Unknown";else if(!e){var e=E(b),d=parseInt(C(b,/\d+\.(\d+)/,
1),10),f=parseInt(C(b,/\d+\.\d+\.(\d+)/,1),10);1<e||1==e&&9<d||1==e&&9==d&&2<=f||b.match(/1\.9\.1b[123]/)!=l||b.match(/1\.9\.1\.[\d\.]+/)}a=new x(a,c,"Gecko",b,A(this),B(this),F(this.p))}else a=ba;return a};function A(a){var c=C(a.c,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=c)return/BB\d{2}/.test(c)&&(c="BlackBerry"),c;a=C(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}
function B(a){var c=C(a.c,/(OS X|Windows NT|Android|CrOS) ([^;)]+)/,2);if(c||(c=C(a.c,/Windows Phone( OS)? ([^;)]+)/,2)))return c;if(c=C(a.c,/(iPhone )?OS ([\d_]+)/,2))return c;if(c=C(a.c,/Linux ([i\d]+)/,1))return c;return(a=C(a.c,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}function E(a){a=C(a,/(\d+)/,1);return""!=a?parseInt(a,10):-1}function C(a,c,b){return(a=a.match(c))&&a[b]?a[b]:""}function F(a){if(a.documentMode)return a.documentMode}
function ca(a,c,b){this.e=a;this.h=c;this.$=b;this.m="wf";this.k=new G("-")}function H(a){v(a.h,a.k.g(a.m,"loading"));w(a.h,a.k.g(a.m,"active"))||u(a.h,a.k.g(a.m,"inactive"));I(a,"inactive")}function I(a,c,b,e){if(a.$[c])a.$[c](b,e)}function J(a,c,b,e,d){this.e=a;this.w=c;this.A=b;this.q=e;this.F=d;this.O=0;this.ra=this.ia=m}
J.prototype.watch=function(a,c,b,e,d){for(var f=a.length,h=0;h<f;h++){var i=a[h];c[i]||(c[i]=["n4"]);this.O+=c[i].length}d&&(this.ia=d);for(h=0;h<f;h++)for(var i=a[h],d=c[i],j=b[i],y=0,va=d.length;y<va;y++){var $=d[y],D=this.w,K=i,aa=$;u(D.h,D.k.g(D.m,K,aa,"loading"));I(D,"fontloading",K,aa);D=p(this,this.za);K=p(this,this.Aa);(new e(D,K,this.e,this.A,this.q,this.F,i,$,j)).start()}};
J.prototype.za=function(a,c){var b=this.w;v(b.h,b.k.g(b.m,a,c,"loading"));v(b.h,b.k.g(b.m,a,c,"inactive"));u(b.h,b.k.g(b.m,a,c,"active"));I(b,"fontactive",a,c);this.ra=k;da(this)};J.prototype.Aa=function(a,c){var b=this.w;v(b.h,b.k.g(b.m,a,c,"loading"));w(b.h,b.k.g(b.m,a,c,"active"))||u(b.h,b.k.g(b.m,a,c,"inactive"));I(b,"fontinactive",a,c);da(this)};
function da(a){0==--a.O&&a.ia&&(a.ra?(a=a.w,v(a.h,a.k.g(a.m,"loading")),v(a.h,a.k.g(a.m,"inactive")),u(a.h,a.k.g(a.m,"active")),I(a,"active")):H(a.w))}
function L(a,c,b,e,d,f,h,i,j){this.ta=a;this.Ea=c;this.e=b;this.A=e;this.q=d;this.F=f;this.Ia=new ea;this.Ca=new fa;this.Q=h;this.P=i;this.Ba=j||"BESbswy";this.ka=ga(this,"arial,'URW Gothic L',sans-serif");this.la=ga(this,"Georgia,'Century Schoolbook L',serif");this.ga=this.ka;this.ha=this.la;this.X=M(this,"arial,'URW Gothic L',sans-serif");this.Y=M(this,"Georgia,'Century Schoolbook L',serif")}L.prototype.start=function(){this.Na=this.F();this.aa()};
L.prototype.aa=function(){var a=this.A.T(this.X),c=this.A.T(this.Y);(this.ka!=a||this.la!=c)&&this.ga==a&&this.ha==c?(a=this.ta,t(this.X),t(this.Y),a(this.Q,this.P)):5E3<=this.F()-this.Na?(a=this.Ea,t(this.X),t(this.Y),a(this.Q,this.P)):(this.ga=a,this.ha=c,ha(this))};function ha(a){a.q(function(a,b){return function(){b.call(a)}}(a,a.aa),25)}function ga(a,c){var b=M(a,c,k),e=a.A.T(b);t(b);return e}function M(a,c,b){c=a.e.createElement("span",{style:ia(a,c,a.P,b)},a.Ba);r(a.e,"body",c);return c}
function ia(a,c,b,e){b=a.Ca.expand(b);return"position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;font-family:"+(e?"":a.Ia.quote(a.Q)+",")+c+";"+b}function G(a){this.Ga=a||"-"}G.prototype.g=function(a){for(var c=[],b=0;b<arguments.length;b++)c.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return c.join(this.Ga)};function ea(){this.pa="'"}
ea.prototype.quote=function(a){for(var c=[],a=a.split(/,\s*/),b=0;b<a.length;b++){var e=a[b].replace(/['"]/g,"");-1==e.indexOf(" ")?c.push(e):c.push(this.pa+e+this.pa)}return c.join(",")};function fa(){this.na=ja;this.B=ka}var ja=["font-style","font-weight"],ka={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function la(a,c,b){this.Fa=a;this.La=c;this.B=b}la.prototype.expand=function(a,c){for(var b=0;b<this.B.length;b++)if(c==this.B[b][0]){a[this.Fa]=this.La+":"+this.B[b][1];break}};fa.prototype.expand=function(a){if(2!=a.length)return l;for(var c=[l,l],b=0,e=this.na.length;b<e;b++){var d=this.na[b];(new la(b,d,this.B[d])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":l};function N(a,c){this.ja=c||a;this.j=document;this.r=g}N.prototype=q.prototype;N.prototype.Da=function(){return this.j.location.hostname};
function ma(a,c,b){var e=a.j.getElementsByTagName("head")[0];if(e){var d=a.j.createElement("script");d.src=c;var f=m;d.onload=d.onreadystatechange=function(){if(!f&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))f=k,b&&b(),d.onload=d.onreadystatechange=l,"HEAD"==d.parentNode.tagName&&e.removeChild(d)};e.appendChild(d)}}N.prototype.qa=function(a,c){this.U()?a.setAttribute("style",c):a.style.cssText=c};
N.prototype.U=function(){if(this.r===g){var a=this.j.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.r=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.r};function na(a){for(var c=a.Ma.join(","),b=[],e=0;e<a.ba.length;e++){var d=a.ba[e];b.push(d.name+":"+d.value+";")}return c+"{"+b.join("")+"}"}function O(a,c){this.z=a;this.D=c;this.da={};this.ca={}}O.prototype.s=function(a){return a?(this.da[a.I]||this.D).slice(0):this.D.slice(0)};
function oa(a,c,b){for(var e=[],d=a.z.split(",")[0].replace(/"|'/g,""),f=a.s(),h,i=[],j={},y=0;y<f.length;y++)h=f[y],0<h.length&&!j[h]&&(j[h]=k,i.push(h));b=b.oa?b.oa(d,i,e):i;c=c.I;a.da[c]=b;a.ca[c]=e}O.prototype.watch=function(a,c,b){var e=[],d={};pa(this,c,e,d);a(e,d,b)};function pa(a,c,b,e){b.push(a.z);e[a.z]=a.s(c);a=a.ca[c.I]||[];for(c=0;c<a.length;c++){for(var d=a[c],f=d.z,h=m,i=0;i<b.length;i++)b[i]==f&&(h=k);h||(b.push(f),e[f]=d.s())}}function qa(a,c){this.z=a;this.D=c}qa.prototype.s=n("D");
function ra(a){var c=new Image(1,1);c.src=a;c.onload=function(){c.onload=l}}function P(a,c){this.I=a;this.fa=c}function sa(){this.ua=this.Qa=this.v=this.G=this.H=k}function Q(a){ta.L.push(a)}function ua(a){this.e=a;this.va=this.o=this.c=this.K=l;this.l=[];this.C=[];this.sa=this.R=this.M=this.N=l}
function wa(a,c){a.c=c;if(a.K){var b;a:{b=a.K;for(var e=a.c,d=a.va,f=0;f<b.L.length;f++){var h=b.L[f],i=e,j=d;j||(j=new sa);if(h.fa&&h.fa(i.getName(),i.getVersion(),i.getEngine(),i.getEngineVersion(),i.getPlatform(),i.getPlatformVersion(),i.getDocumentMode(),j)){b=h;break a}}b=l}a.o=b}}o=ua.prototype;o.supportsConfiguredBrowser=function(){return!!this.o};
o.init=function(){if(0<this.C.length){for(var a=[],c=0;c<this.C.length;c++)a.push(na(this.C[c]));var c=this.e,a=a.join(""),b=this.e.j.createElement("style");b.setAttribute("type","text/css");b.styleSheet?b.styleSheet.cssText=a:b.appendChild(document.createTextNode(a));r(c,"head",b)}};
o.load=function(a,c){var b=this.o.I;if(this.R)for(var e=xa(this.R,b),d=0;d<this.l.length;d++)oa(this.l[d],this.o,e);this.N&&(e=[],this.M&&(e=new ya(this.e,this.o,this.l),e=za(this.M,b,e)),b=this.N.g("https:"==this.e.j.location.protocol,Aa(b,e)),r(this.e,"head",this.e.createElement("link",{rel:"stylesheet",href:b})));a&&s(function(a,b,c,d){return function(){for(var e=0;e<a.l.length;e++)a.l[e].watch(b,c,d&&e==a.l.length-1)}}(this,a,this.o,c))};
o.collectFontFamilies=function(a,c){for(var b=0;b<this.l.length;b++)pa(this.l[b],this.o,a,c)};o.performOptionalActions=function(a){this.V&&s(function(a,b,e,d){return function(){var b=a.V;if(b.ma){var h=window.__adobewebfontsappname__,h=h?h.toString().substr(0,20):"";ra(b.ma.g("https:"==d.j.location.protocol,{host:encodeURIComponent(d.j.location.hostname),app:encodeURIComponent(h),_:(+new Date).toString()}))}b=a.V;b.Z&&(b=b.Z.g(e,d),r(d,"body",b))}}(this,a,this.c,this.e))};
function R(a,c,b,e){this.Ha=a;this.e=c;this.h=b;this.q=e;this.n=[]}R.prototype.J=function(a){this.n.push(a)};R.prototype.load=function(a,c){var b=a,e=c||{};if("string"==typeof b)b=[b];else if(!b||!b.length)e=b||{},b=[];if(b.length)for(var d=this,f=b.length,h=0;h<b.length;h++)Ba(this,b[h],function(){0==--f&&Ca(d,e)});else Ca(this,e)};function Ba(a,c,b){ma(a.e,a.Ha.g("https:"==a.e.j.location.protocol,{id:encodeURIComponent(c)}),b)}
function Ca(a,c){if(0!=a.n.length){for(var b=new ca(a.e,a.h,c),e=m,d=0;d<a.n.length;d++)a.n[d].init(),e=e||a.n[d].supportsConfiguredBrowser();e?(u(b.h,b.k.g(b.m,"loading")),I(b,"loading"),Da(a,b)):H(b);a.n=[]}}function Da(a,c){function b(a,b,c){e.watch(a,b,{},L,c)}for(var e=new J(a.e,c,{T:function(a){return a.offsetWidth}},a.q,function(){return+new Date}),d=0;d<a.n.length;d++){var f=a.n[d];f.supportsConfiguredBrowser()&&(f.load(b,d==a.n.length-1),f.performOptionalActions(window))}}
function S(a,c){this.ea=a;this.q=c;this.n=[]}S.prototype.J=function(a){this.n.push(a)};S.prototype.load=function(){var a=this.ea.__webfonttypekitmodule__;if(a)for(var c=0;c<this.n.length;c++){var b=this.n[c],e=a[b.sa];if(e){var d=this.q;e(function(a,c,e){var c=[],j={};wa(b,a);b.supportsConfiguredBrowser()&&(b.init(),b.load(l,d),b.collectFontFamilies(c,j),b.performOptionalActions(window));e(b.supportsConfiguredBrowser(),c,j)})}}};function T(a,c){this.W=a;this.oa=c}T.prototype.getName=n("W");
function Ea(a){var c=U;Fa(c,a.getName())||c.S.push(a)}function Fa(a,c){for(var b=0;b<a.S.length;b++){var e=a.S[b];if(c===e.getName())return e}return l}function xa(a,c){var b=a.t[c];return b?Fa(a,b):l}function za(a,c,b){for(var e=[],a=a.u[c]||[],c=0;c<a.length;c++){var d;a:switch(a[c]){case "observeddomain":d=new Ga(b.e);break a;case "fontmask":d=new Ha(b.o,b.l);break a;default:d=l}d&&e.push(d)}return e}function ya(a,c,b){this.e=a;this.o=c;this.l=b}function Ga(a){this.e=a}
Ga.prototype.toString=function(){return encodeURIComponent(this.e.Da?this.e.j.location.hostname:document.location.hostname)};function Ha(a,c){this.o=a;this.l=c}Ha.prototype.toString=function(){for(var a=[],c=0;c<this.l.length;c++)for(var b=this.l[c],e=b.s(),b=b.s(this.o),d=0;d<e.length;d++){var f;a:{for(f=0;f<b.length;f++)if(e[d]===b[f]){f=k;break a}f=m}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");c=[];for(e=a.length;0<e;e-=4)b=a.slice(0>e-4?0:e-4,e),c.unshift(parseInt(b,2).toString(16));return c.join("")};
function V(a){this.Oa=a}V.prototype.g=function(a,c){var b=c||{},e=this.Oa.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,c,e){return e&&b[c]?"/"+b[c].join("/"):b[c]||""});e.match(/^\/\//)&&(e=(a?"https:":"http:")+e);return e.replace(/\/*\?*($|\?)/,"$1")};function Aa(a,c){for(var b=[],e=0;e<c.length;e++)b.push(c[e].toString());return{format:a,extras:b}}var ta=new function(){this.L=[]};
Q(new P("a",function(a,c,b,e,d,f){if(m||("Windows"==d&&"Unknown"==f?k:m)||("Ubuntu"==d||"Linux"==d?k:m))a:{if("AdobeAIR"==a&&(a=/([0-9]+.[0-9]+)/.exec(c))){a=2.5<=parseFloat(a[1]);break a}a=m}else a=m;return a}));
Q(new P("b",function(a,c,b,e,d,f,h,i){var j;j=m||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?k:m}(a,c,b,e,d,f,h,i);return!j?m:function(a,b){if("AdobeAIR"==a){var c=/([0-9]+.[0-9]+)/.exec(b);if(c)return 2.5<=parseFloat(c[1])}return m}(a,c,b,e,d,f,h,i)}));
Q(new P("a",function(a,c,b,e,d,f,h,i){if(!(c=m))f=/([0-9]+).([0-9]+)/.exec(f),i.v&&"Android"==d&&f?(d=parseInt(f[1],10),i=parseInt(f[2],10),c=2==d&&2<=i||3==d&&1>i):c=m;return!c?m:"BuiltinBrowser"==a}));Q(new P("f",function(a,c,b,e,d,f,h,i){if(!(c=m))f=/([0-9]+).([0-9]+)/.exec(f),i.v&&"Android"==d&&f?(d=parseInt(f[1],10),i=parseInt(f[2],10),c=3==d&&1<=i||3<d):c=m;return!c?m:"BuiltinBrowser"==a}));Q(new P("d",function(a,c,b,e,d,f,h,i){c=m||i.ua&&10<=parseInt(f,10);return!c?m:"BuiltinBrowser"==a}));
Q(new P("a",function(a,c,b,e,d,f,h,i){var j;j=(j=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m)||("Windows"==d&&"6.0"==f?k:m)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):m}(a,c,b,e,d,f,h,i))||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:m}(a,c,b,e,d,f,h,i);return!j&&!("Ubuntu"==
d||"Linux"==d?k:m)?m:function(a,b){if("Chrome"==a){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c){var d=parseFloat(c[1]),e=parseInt(c[2],10),c=parseInt(c[3],10);if(!(6<=d)&&(4<d||4==d&&249<e||4==d&&249==e&&4<=c))return k}}return m}(a,c,b,e,d,f,h,i)}));
Q(new P("d",function(a,c,b,e,d,f,h,i){var j;j=(j=(j=(j=(j=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m)||("Windows"==d&&"6.0"==f?k:m)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):m}(a,c,b,e,d,f,h,i))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?k:m}(a,c,b,e,d,f,h,i))||("Ubuntu"==
d||"Linux"==d?k:m)||function(a,b,c,e,d,f,h,i){a=/([0-9]+).([0-9]+)/.exec(f);return i.v&&"Android"==d&&a?(d=parseInt(a[1],10),i=parseInt(a[2],10),3==d&&1<=i||3<d):m}(a,c,b,e,d,f,h,i))||"CrOS"==d||function(a,b,c,d,e,f,i,h){return h.G&&"iPad"==e?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):m:m}(a,c,b,e,d,f,h,i))||function(a,b,c,e,d,f,h,i){return i.H&&("iPhone"==d||"iPod"==d)?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):m:m}(a,c,b,e,d,f,h,i);return!j?m:function(a,b){if("Chrome"==a){var c=
/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c&&6<=parseFloat(c[1]))return k}}(a,c,b,e,d,f,h,i)}));
Q(new P("a",function(a,c,b,e,d,f,h,i){var j;j=(j=m||function(a,b,c,d,e,f,i,h){return h.G&&"iPad"==e&&(a=/^([0-9]+)_([0-9]+)/.exec(f))?(b=parseInt(a[2],10),4==parseInt(a[1],10)&&2<=b):m}(a,c,b,e,d,f,h,i))||function(a,b,c,d,e,f,h,i){if(i.H&&("iPhone"==e||"iPod"==e))if(a=/^([0-9]+)_([0-9]+)/.exec(f))return b=parseInt(a[2],10),4==parseInt(a[1],10)&&2<=b;return m}(a,c,b,e,d,f,h,i);return!j?m:function(a,b){if("Chrome"==a){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c&&6<=parseFloat(c[1]))return k}}(a,
c,b,e,d,f,h,i)}));Q(new P("a",function(a,c,b,e,d,f,h,i){var j;j=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m)||("Windows"==d&&"6.0"==f?k:m)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):m}(a,c,b,e,d,f,h,i);return!j&&!("Ubuntu"==d||"Linux"==d?k:m)?m:function(a,b,c,d){return"Gecko"==c?(a=/1.9.1b[1-3]{1}/,/1.9.1/.test(d)&&!a.test(d)):m}(a,c,b,e,d,f,h,i)}));
Q(new P("b",function(a,c,b,e,d,f,h,i){var j;j=m||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?k:m}(a,c,b,e,d,f,h,i);return!j?m:function(a,b,c,d){return"Gecko"==c?(a=/1.9.1b[1-3]{1}/,/1.9.1/.test(d)&&!a.test(d)):m}(a,c,b,e,d,f,h,i)}));
Q(new P("d",function(a,c,b,e,d,f,h,i){var j;j=(j=(j=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m)||("Windows"==d&&"6.0"==f?k:m)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):m}(a,c,b,e,d,f,h,i))||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:m}(a,c,b,e,d,f,h,i))||("Ubuntu"==
d||"Linux"==d?k:m)||i.v&&"Android"==d;return!j?m:function(a,b,c,d){return"Gecko"==c&&(b=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(d))?(a=parseFloat(b[1]),b=parseInt(b[3],10),1.9<a||1.9<=a&&1<b):m}(a,c,b,e,d,f,h,i)}));
Q(new P("i",function(a,c,b,e,d,f,h,i){var j;j=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m)||("Windows"==d&&"6.0"==f?k:m)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):m}(a,c,b,e,d,f,h,i);return!j?m:function(a,b,c,d,e,f,i){if("MSIE"==a)return(a=/([0-9]+.[0-9]+)/.exec(b))?6<=parseFloat(a[1])&&(i===g||9>i):m}(a,c,b,e,d,f,h,i)}));
Q(new P("d",function(a,c,b,e,d,f,h){if(!(c=m))b=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&b?(c=parseInt(b[1],10),b=parseInt(b[2],10),c=6<c||6==c&&1<=b):c=m;a=c||("Windows"==d&&"6.0"==f?k:m)?"MSIE"==a?9<=h:g:m;return a}));Q(new P("d",function(a,c,b,e,d,f,h,i){if(!(c=m))f=/^([0-9]+)/.exec(f),c=i.Qa&&"Windows Phone"==d&&f?8<=parseInt(f[1],10):m;return!c?m:"MSIE"==a}));
Q(new P("a",function(a,c,b,e,d,f,h,i){var j;j=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m)||("Windows"==d&&"6.0"==f?k:m)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):m}(a,c,b,e,d,f,h,i);return!j&&!("Ubuntu"==d||"Linux"==d?k:m)?m:function(a,b){if("Opera"==a){var c=parseFloat(b);return 10.54<=c&&11.1>c}return m}(a,c,b,e,d,f,h,i)}));
Q(new P("b",function(a,c,b,e,d,f,h,i){var j;j=m||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:m}(a,c,b,e,d,f,h,i);return!j?m:function(a,b){if("Opera"==a){var c=parseFloat(b);return 10.54<=c&&11.1>c}return m}(a,c,b,e,d,f,h,i)}));
Q(new P("d",function(a,c,b,e,d,f,h,i){var j;j=(j=(j=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m)||("Windows"==d&&"6.0"==f?k:m)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):m}(a,c,b,e,d,f,h,i))||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:m}(a,c,b,e,d,f,h,i))||("Ubuntu"==
d||"Linux"==d?k:m)||i.v&&"Android"==d;return!j?m:"Opera"==a?11.1<=parseFloat(c):m}));Q(new P("b",function(a,c,b,e,d,f,h,i){var j;j=m||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?k:m}(a,c,b,e,d,f,h,i);return!j?m:function(a,b,c,e){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(e))?(a=parseFloat(a[1]),525.13<=a&&534.5>a):m}(a,c,b,e,d,f,h,i)}));
Q(new P("a",function(a,c,b,e,d,f,h,i){var j;j=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m)||("Windows"==d&&"6.0"==f?k:m)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):m}(a,c,b,e,d,f,h,i);return!j?m:function(a,b,c,d){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(d))?(a=parseFloat(a[1]),525.13<=a&&534.5>a):m}(a,c,b,e,d,f,h,i)}));
Q(new P("d",function(a,c,b,e,d,f,h,i){var j;j=(j=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m)||("Windows"==d&&"6.0"==f?k:m)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):m}(a,c,b,e,d,f,h,i))||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:m}(a,c,b,e,d,f,h,i);return!j?m:function(a,
b,c,d){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(d))?534.5<=parseFloat(a[1]):m}(a,c,b,e,d,f,h,i)}));
Q(new P("a",function(a,c,b,e,d,f,h,i){var j;j=(j=m||function(a,b,c,d,e,f,i,h){return h.G&&"iPad"==e&&(a=/^([0-9]+)_([0-9]+)/.exec(f))?(b=parseInt(a[2],10),4==parseInt(a[1],10)&&2<=b):m}(a,c,b,e,d,f,h,i))||function(a,b,c,d,e,f,i,h){if(h.H&&("iPhone"==e||"iPod"==e))if(a=/^([0-9]+)_([0-9]+)/.exec(f))return b=parseInt(a[2],10),4==parseInt(a[1],10)&&2<=b;return m}(a,c,b,e,d,f,h,i);return!j?m:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==d||"iPad"==d)?k:m}));
Q(new P("d",function(a,c,b,e,d,f,h,i){var j;j=(j=m||function(a,b,c,d,e,f,i,h){return h.G&&"iPad"==e?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):m:m}(a,c,b,e,d,f,h,i))||function(a,b,c,d,e,f,i,h){return h.H&&("iPhone"==e||"iPod"==e)?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):m:m}(a,c,b,e,d,f,h,i);return!j?m:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==d||"iPad"==d)?k:m}));var U=new function(){this.S=[];this.t={}};Ea(new T("AllFonts",function(a,c){return c}));
Ea(new T("DefaultFourFontsWithSingleFvdFamilies",function(a,c,b){for(var e=0;e<c.length;e++){var d=c[e],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+d;b.push(new qa(f,[d]))}a={};for(d=0;d<c.length;d++)b=c[d],e=b.charAt(1),(a[e]||(a[e]=[])).push(b);b=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];e=[];for(d=0;d<b.length;d++)for(var f=b[d],h=0;h<f.length;h++){var i=f[h];if(a[i]){e=e.concat(a[i]);break}}b=e;e={};a=[];for(d=0;d<b.length;d++)f=b[d],e[f]||(e[f]=k,a.push(f));b=[];for(e=0;e<c.length;e++){d=c[e];
for(f=0;f<a.length;f++)h=a[f],h==d&&b.push(h)}return b}));U.t.a="AllFonts";U.t.b="AllFonts";U.t.d="AllFonts";U.t.f="AllFonts";U.t.i="DefaultFourFontsWithSingleFvdFamilies";var W=new function(){this.u={}};W.u.a=[];W.u.b=[];W.u.d=[];W.u.f=["observeddomain"];W.u.i=["observeddomain","fontmask"];window.Typekit||(window.Typekit={});
if(!window.Typekit.load){var Ia=function(a,c){setTimeout(a,c)},X=new R(new V("//fonts.nymag.com/{id}.js"),new N(window),document.documentElement,Ia),Y=new S(window,Ia);window.Typekit.load=function(){X.load.apply(X,arguments)};window.Typekit.addKit=function(){X.J.apply(X,arguments)}}var Ja=l,Ka,Z,Ja=new V("//p.typekit.net/p.gif?a=71&f=7179&h={host}&ht=sh&k=ajl3knu&s=1&_={_}");Ka=new function(){var a=Ja;this.Z=l;this.ma=a};Z=new ua(new N(window));Z.sa="ajl3knu";Z.N=new V("//fonts.nymag.com/k/ajl3knu-{format}.css?3bb2a6e53c9684ffdc9a99f61e5b2a6226619738cdb374f11f2f310322a6b9d78f2c8ca293a27b58fde7107b0d92afde92f47c760dd00928a18b2f695e054d5b250b0dae770c35b1fd6ab976b96bea68a90ecf99029f7f939709fdf365236ec2550b3c816a378fd4abf394715a9ea110e9898721aa3ce8a85eca39190a6d4326ec94b48c00589316034b6f457ce702b162038dd21360a82c098b8dc11a54b22cb0c1d7e19da5ab9782992741094a572aed7e38696e40c9827fd6cf7fae7c8997a1f4cb74258e2f38d791592a4e120db2ea0686f53d46e6ae6b4f5d43acce1e5cb6c14943f46df9a6184dd3309b1f035acd267cd30429d5e0d5052a98131eab44271e7fc266d71d72f1b3a1f04e9c30279542f3b180d6928b2c297cb6da4db4c2be1699d019867d742a559ae59104d832");
Z.V=Ka;Z.l.push(new O("elderkin",["n7"]));Z.C.push(new function(){this.Ma=[".tk-elderkin"];this.ba=[{name:"font-family",value:'"elderkin",sans-serif'}]});Z.K=ta;Z.M=W;Z.R=U;Y&&Y.ea.__webfonttypekitmodule__?(Y.J(Z),Y.load()):(wa(Z,(new z(navigator.userAgent,document)).parse()),window.Typekit.addKit(Z));
})(this,document);